name: Build/Test Plugins

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./

      -
        name: Install just
        uses: extractions/setup-just@v1

      -
        name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      # Saves us from having to redownload all modules
      - name: Go Mod cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      -
        name: Test
        run: |
          just test-all-plugins

      -
        name: Build
        run: |
          just build-all-plugins
      - name: get-pr-info
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: |
          echo $PR_NUM > pr_num.txt
          echo $GITHUB_BASE_REF > base.txt
          echo $GITHUB_HEAD_REF > head.txt

      - name: Upload code coverage
        uses: actions/upload-artifact@v4
        with:
          name: oc-code-coverage
          path: |
           *.out
           pr_num.txt
           base.txt
           head.txt
