name: Build and Release Plugins

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-publish-plugins:
    runs-on: ubuntu-latest
    steps: 
      -  name: checkout
         uses: actions/checkout@v4
         with:
           path: ./

      - name: Install just
        uses: extractions/setup-just@v1

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      # Saves us from having to redownload all modules
      - name: Go Mod cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Build
        run: |
          just build-all-plugins

      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          files: build/*
          fail_on_unmatched_files: true
